name: shop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  form_field_validator: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_widget_from_html_core: ^0.16.0
  animations: ^2.0.11
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  http: ^1.3.0
#  firebase_core: ^3.12.1
#  firebase_auth: ^5.5.1
#  cloud_firestore: ^5.6.5
#  firebase_data_connect: ^0.1.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/login_dark.png
    - assets/images/login_light.png
    - assets/images/notification.png
    - assets/images/signUp_dark.png
    - assets/images/signUp_light.png
    - assets/icons/Accessories.svg
    - assets/icons/Arrow - Down.svg
    - assets/icons/Arrow - Left.svg
    - assets/icons/Arrow - Right.svg
    - assets/icons/Arrow - Up.svg
    - assets/icons/Bag.svg
    - assets/icons/bag_full.svg
    - assets/icons/Behance.svg
    - assets/icons/Bookmark.svg
    - assets/icons/Calender.svg
    - assets/icons/Call.svg
    - assets/icons/Camera-add.svg
    - assets/icons/Camera-Bold.svg
    - assets/icons/card.svg
    - assets/icons/Card_Pattern.svg
    - assets/icons/Cash.svg
    - assets/icons/Category.svg
    - assets/icons/Chat.svg
    - assets/icons/Chat-add.svg
    - assets/icons/Child.svg
    - assets/icons/Clock.svg
    - assets/icons/Close.svg
    - assets/icons/Close-Circle.svg
    - assets/icons/Coupon.svg
    - assets/icons/CVV.svg
    - assets/icons/Danger Circle.svg
    - assets/icons/Delete.svg
    - assets/icons/Delivery.svg
    - assets/icons/diamond.svg
    - assets/icons/Discount.svg
    - assets/icons/Discount_tag.svg
    - assets/icons/Dislike.svg
    - assets/icons/dot.svg
    - assets/icons/DotsH.svg
    - assets/icons/DotsV.svg
    - assets/icons/Doublecheck.svg
    - assets/icons/Dribbble.svg
    - assets/icons/Edit Square.svg
    - assets/icons/Edit-Bold.svg
    - assets/icons/Emoji.svg
    - assets/icons/Facebook.svg
    - assets/icons/FaceId.svg
    - assets/icons/FAQ.svg
    - assets/icons/Filter.svg
    - assets/icons/Fingerprint.svg
    - assets/icons/Flashlight.svg
    - assets/icons/Gift.svg
    - assets/icons/Help.svg
    - assets/icons/Image.svg
    - assets/icons/info.svg
    - assets/icons/Instagram.svg
    - assets/icons/Language.svg
    - assets/icons/Like.svg
    - assets/icons/Link.svg
    - assets/icons/Linkedin.svg
    - assets/icons/Loading.svg
    - assets/icons/Location.svg
    - assets/icons/Lock.svg
    - assets/icons/Logout.svg
    - assets/icons/Man&Woman.svg
    - assets/icons/Man.svg
    - assets/icons/Message.svg
    - assets/icons/miniDown.svg
    - assets/icons/miniLeft.svg
    - assets/icons/miniRight.svg
    - assets/icons/miniTop.svg
    - assets/icons/Minus.svg
    - assets/icons/Mylocation.svg
    - assets/icons/Newcard.svg
    - assets/icons/Notification.svg
    - assets/icons/Order.svg
    - assets/icons/Payonline.svg
    - assets/icons/Plus1.svg
    - assets/icons/Preferences.svg
    - assets/icons/Product.svg
    - assets/icons/Profile.svg
    - assets/icons/Return.svg
    - assets/icons/Sale.svg
    - assets/icons/Scan.svg
    - assets/icons/Search.svg
    - assets/icons/Send.svg
    - assets/icons/Setting.svg
    - assets/icons/Share.svg
    - assets/icons/Shop.svg
    - assets/icons/Show.svg
    - assets/icons/Singlecheck.svg
    - assets/icons/Sizeguid.svg
    - assets/icons/Sort.svg
    - assets/icons/Standard.svg
    - assets/icons/Star.svg
    - assets/icons/Star-bold.svg
    - assets/icons/Star_filled.svg
    - assets/icons/Stores.svg
    - assets/icons/Trackorder.svg
    - assets/icons/twitter.svg
    - assets/icons/Wallet.svg
    - assets/icons/Wishlist.svg
    - assets/icons/Woman.svg
    - assets/icons/world_map.svg
    - assets/Illustration/Illustration-0.png
    - assets/Illustration/Illustration-1.png
    - assets/Illustration/Illustration-2.png
    - assets/Illustration/Illustration-3.png
    - assets/Illustration/Illustration-4.png
    - assets/Illustration/Illustration_darkTheme_0.png
    - assets/Illustration/Illustration_darkTheme_1.png
    - assets/Illustration/Illustration_darkTheme_2.png
    - assets/Illustration/Illustration_darkTheme_3.png
    - assets/Illustration/Illustration_darkTheme_4.png
    - assets/Illustration/EmptyState_darkTheme.png
    - assets/Illustration/EmptyState_lightTheme.png
    - assets/Illustration/faceId.png
    - assets/Illustration/faceId_dark.png
    - assets/Illustration/Failed_darkTheme.png
    - assets/Illustration/Failed_lightTheme.png
    - assets/Illustration/fingerprint.png
    - assets/Illustration/fingerprint_dark.png
    - assets/Illustration/Help_darkTheme.png
    - assets/Illustration/Help_lightTheme.png
    - assets/Illustration/no_internet.png
    - assets/Illustration/no_internet_dark.png
    - assets/Illustration/NoResult.png
    - assets/Illustration/NoResultDarkTheme.png
    - assets/Illustration/Password.png
    - assets/Illustration/Password_dark.png
    - assets/Illustration/PayWithCash_darkTheme.png
    - assets/Illustration/PayWithCash_lightTheme.png
    - assets/Illustration/server_error.png
    - assets/Illustration/server_error_dark.png
    - assets/Illustration/success.png
    - assets/Illustration/success_dark.png
    - assets/Illustration/Success_darkTheme.png
    - assets/Illustration/Success_lightTheme.png
    - assets/Illustration/TurnOnNotification_darkTheme.png
    - assets/Illustration/TurnOnNotification_lightTheme.png
    - assets/Illustration/VerificationCode_dark.png
    - assets/flags/England.svg
    - assets/flags/france.svg
    - assets/flags/German.svg
    - assets/flags/India.svg
    - assets/flags/Italy.svg
    - assets/flags/japanese.svg
    - assets/logo/Shoplon.svg
    - assets/screens/Add review rate.png
    - assets/screens/Addresses.png
    - assets/screens/Cancel order - Select a reason.png
    - assets/screens/Cart_1.png
    - assets/screens/Cart_2.png
    - assets/screens/Cart_3.png
    - assets/screens/Cart_4.png
    - assets/screens/Cart_5.png
    - assets/screens/Cart_6.png
    - assets/screens/Edit profile.png
    - assets/screens/Enable notification.png
    - assets/screens/Enter verification code.png
    - assets/screens/Forgot password 6.png
    - assets/screens/Forgot_password.png
    - assets/screens/Kids.png
    - assets/screens/No notification.png
    - assets/screens/Notification.png
    - assets/screens/notification setting.png
    - assets/screens/On sales.png
    - assets/screens/Orders.png
    - assets/screens/Product detail.png
    - assets/screens/Profile.png
    - assets/screens/Reset password.png
    - assets/screens/reviews.png
    - assets/screens/SEARCH_1.png
    - assets/screens/Search_2.png
    - assets/screens/Search_3.png
    - assets/screens/Search_4.png
    - assets/screens/Search_5.png
    - assets/screens/Search_6.png
    - assets/screens/Search_7.png
    - assets/screens/Search_8.png
    - assets/screens/Shipping information.png
    - assets/screens/Size Guide.png
    - assets/screens/Verificaition code.png

  fonts:
    - family: Plus Jakarta
      fonts:
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Regular.otf
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/plus_jakarta/PlusJakartaDisplay-Bold.otf
          weight: 700
    - family: Grandis Extended
      fonts:
        - asset: assets/fonts/grandis_extended/GrandisExtended-Regular.ttf
        - asset: assets/fonts/grandis_extended/GrandisExtended-Thin.ttf
          weight: 300
        - asset: assets/fonts/grandis_extended/GrandisExtended-Medium.ttf
          weight: 500
        - asset: assets/fonts/grandis_extended/GrandisExtended-Bold.ttf
          weight: 700
        - asset: assets/fonts/grandis_extended/GrandisExtended-Black.ttf
          weight: 900
